//! The bindings are generated by proc macros that read the XML at expansion
//! time, which Cargo cannot see. Without this, editing the protocol leaves the
//! previously generated code in place and the change appears to do nothing.

fn main() {
    println!("cargo:rerun-if-changed=protocols/lxb-shell-v1.xml");
}
